[package]
name = "automove"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.51"
serde = "1.0.130"
serde_derive = "1.0.130"
toml = "0.5.8"
